import Head from 'next/head';
import { Button } from '@chakra-ui/button';
import { InputGroup, InputRightElement } from '@chakra-ui/react';
import { styled } from 'styled-components';
import { Heading } from '@chakra-ui/react';
import { Input } from '@chakra-ui/react';
import { useState } from 'react';
import NextLink from 'next/link';
import { Text, Link } from '@chakra-ui/react';

const MainStyled = styled.main`
  display: flex;
  flex-direction: column;
  align-items: center;
  margin: 120px 0;
  padding: 10px;
`;
const InputContainerStyled = styled.div`
  display: flex;
  flex-direction: column;
  gap: 20px;
  align-items: center;
  padding: 20px;
  width: 50%;
`;

export const index = () => {
  const [showPassword, setShowPassword] = useState(false);
  const handleClick = () => setShowPassword(!showPassword);
  return (
    <>
      <Head>
        <title>LoginPage</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <MainStyled>
        <Heading
          as='h2'
          size='3xl'
          fontFamily='Georgia'
          fontWeight='bold'
          color='#4267B2'
          mb={15}
        >
          Student Login
        </Heading>

        <InputContainerStyled>
          <Input
            placeholder='Username'
            size='lg'
            variant='flushed'
            focusBorderColor='#4267B2'
          />

          <InputGroup size='lg'>
            <Input
              pr='20px'
              type={showPassword ? 'text' : 'password'}
              placeholder='Password'
              size='lg'
              variant='flushed'
              focusBorderColor='#4267B2'
            />
            <InputRightElement width='4.5rem'>
              <Button h='1.75rem' size='sm' onClick={handleClick}>
                {showPassword ? 'Hide' : 'Show'}
              </Button>
            </InputRightElement>
          </InputGroup>
          <Button colorScheme='green' variant='solid' mt={10}>
            Login
          </Button>
          <Link as={NextLink} href='/home' color='#4267B2' fontSize='25px'>
            Forgot Password
          </Link>
          <Text fontSize='25px'>
            Not Registered Yet?{'  '}
            <Link color='#4267B2' href='/signup' fontSize='25px'>
              Register Now...
            </Link>
          </Text>
        </InputContainerStyled>
      </MainStyled>
    </>
  );
};
export default index;
