import Head from 'next/head';
import { Button } from '@chakra-ui/button';
import { Box, InputGroup, InputRightElement } from '@chakra-ui/react';
import { styled } from 'styled-components';
import { Heading } from '@chakra-ui/react';
import { Input } from '@chakra-ui/react';
import NextLink from 'next/link';
import { Text, Link } from '@chakra-ui/react';
import { MdArrowBackIosNew } from 'react-icons/md';
import { Auth } from '@supabase/auth-ui-react';
import { ThemeSupa } from '@supabase/auth-ui-shared';
import { useUser, useSupabaseClient } from '@supabase/auth-helpers-react';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';

const InputContainerStyled = styled.div`
  display: flex;
  flex-direction: column;
  gap: 20px;
  align-items: center;
  padding: 20px;
  width: 50%;
`;
const StyledFooter = styled.footer`
  bottom: 0;
  position: fixed;
  width: 100%;
  background-color: #002147;
  color: #fff;
  text-align: center;
  line-height: 50px;
  margin-top: 3%;
`;
const StyledIcon = styled.h1`
  font-size: 42px;
  font-weight: 700;
  color: #0c2b50;
`;

const AuthStyled = styled(Auth)`
  padding: 300px;
`;

export const Index = () => {
  const supabaseClient = useSupabaseClient();
  const user = useUser();
  const [data, setData] = useState();

  const router = useRouter();

  useEffect(() => {
    if (user) router.push('/scholars');
  }, [user, router]);

  const [showPassword, setShowPassword] = useState(false);
  const handleClick = () => setShowPassword(!showPassword);

  if (!user) {
    return (
      <>
        <>
          <Head>
            <title>LoginPage</title>
            <meta name='description' content='Generated by create next app' />
            <meta
              name='viewport'
              content='width=device-width, initial-scale=1'
            />
          </Head>
          <Box
            display={'flex'}
            margin={'0 20%'}
            alignItems={'center'}
            height={'100px'}
            width={'50%'}
          >
            <Link href='/'>
              <StyledIcon>{<MdArrowBackIosNew size={36} />}</StyledIcon>
            </Link>
            <Heading
              marginLeft={'43%'}
              as={'h1'}
              color={'teal'}
              fontWeight={700}
            >
              Login Page
            </Heading>
          </Box>
          <main>
            {!user ? (
              <Auth
                redirectTo='http://localhost:3000/'
                localization={{
                  variables: {
                    sign_in: {
                      email_label: '',
                      password_label: '',
                      email_input_placeholder: 'Username',
                      password_input_placeholder: 'Password',
                    },
                  },
                }}
                appearance={{
                  theme: ThemeSupa,
                  variables: {
                    default: {
                      colors: {
                        brand: 'rgb(56, 161, 105)',
                        brandAccent: 'rgb(28, 134, 78)',
                      },
                    },
                  },
                  style: {
                    button: {
                      fontSize: '20px',
                      fontWeight: '600',
                      flexBasis: '50%',
                      width: '40%',
                      margin: '0 auto',
                    },
                    anchor: {
                      color: 'black',
                      fontSize: '20px',
                      textDecoration: 'none',
                    },
                    container: {
                      margin: '20px 20%',
                    },
                    label: {},
                    input: { width: '100%' },
                    loader: {},
                    message: {
                      fontWeight: 'bold',
                    },
                    divider: {},
                  },
                }}
                supabaseClient={supabaseClient}
                providers={[]}
                socialLayout='horizontal'
              />
            ) : (
              <></>
            )}
          </main>
          <StyledFooter>
            © 2023 - Islamic University of Science and Technology.
          </StyledFooter>
        </>
      </>
    );
  }
};
export default Index;
