import Head from 'next/head';
import { Box } from '@chakra-ui/react';
import { Heading } from '@chakra-ui/react';
import { Link } from '@chakra-ui/react';
import { Auth } from '@supabase/auth-ui-react';
import { ThemeSupa } from '@supabase/auth-ui-shared';
import { useUser, useSupabaseClient } from '@supabase/auth-helpers-react';
import { useEffect } from 'react';
import { useRouter } from 'next/router';
import BackIcon from '@/components/BackIcon/BackIcon';
import InnerFooter from '@/components/InnerFooter/InnerFooter';
import { fetchUserDetails } from '@/utils/utils';

export const Index = () => {
  const supabaseClient = useSupabaseClient();
  const user = useUser();
  const router = useRouter();

  useEffect(() => {
    if (user) {
      const fetchDataFromApi = async () => {
        try {
          const data = await fetchUserDetails(user.email || '');
          switch (data.role) {
            case 'scholar':
              router.push(`/protected/scholars/${user.email}`);
              break;
            case 'supervisor':
              router.push(`/protected/supervisor/${user.email}`);
              break;
            case 'office-staff':
              router.push(`/protected/office`);
              break;
            case 'drc-staff':
              router.push(`/protected/drc`);
              break;
            case 'srac-member':
              // Handle what happens if srac member logs in
              break;
            default:
              break;
          }
        } catch (error) {
          console.error('Error fetching data:', error);
        }
      };

      fetchDataFromApi();
    }
  });

  if (!user) {
    return (
      <>
        <>
          <Head>
            <title>LoginPage</title>
            <meta name='description' content='Generated by create next app' />
            <meta
              name='viewport'
              content='width=device-width, initial-scale=1'
            />
          </Head>
          <Box
            display={'flex'}
            margin={'0 20%'}
            alignItems={'center'}
            height={'100px'}
            width={'50%'}
          >
            <Link href='/'>
              <BackIcon />
            </Link>
            <Heading
              marginLeft={'43%'}
              as={'h1'}
              color={'teal'}
              fontWeight={700}
            >
              Login Page
            </Heading>
          </Box>
          <main>
            <Auth
              redirectTo='http://localhost:3000/'
              localization={{
                variables: {
                  sign_in: {
                    email_label: '',
                    password_label: '',
                    email_input_placeholder: 'Username',
                    password_input_placeholder: 'Password',
                  },
                },
              }}
              appearance={{
                theme: ThemeSupa,
                variables: {
                  default: {
                    colors: {
                      brand: 'rgb(56, 161, 105)',
                      brandAccent: 'rgb(28, 134, 78)',
                    },
                  },
                },
                style: {
                  button: {
                    fontSize: '20px',
                    fontWeight: '600',
                    flexBasis: '50%',
                    width: '40%',
                    margin: '0 auto',
                  },
                  anchor: {
                    color: 'black',
                    fontSize: '20px',
                    textDecoration: 'none',
                  },
                  container: {
                    margin: '20px 20%',
                    marginBottom: '4%',
                  },
                  label: {},
                  input: { width: '100%' },
                  loader: {},
                  message: {
                    fontWeight: 'bold',
                  },
                  divider: {},
                },
              }}
              supabaseClient={supabaseClient}
              providers={[]}
              socialLayout='horizontal'
            />
          </main>
          <br />
          <br />
        </>
        <InnerFooter />
      </>
    );
  }
};
export default Index;
