import Head from 'next/head';
import { Button } from '@chakra-ui/button';
import { Box, InputGroup, InputRightElement, Link } from '@chakra-ui/react';
import { styled } from 'styled-components';
import { Heading } from '@chakra-ui/react';
import { Input } from '@chakra-ui/react';
import { useState } from 'react';
import BackIcon from '@/components/BackIcon/BackIcon';
import InnerFooter from '@/components/InnerFooter/InnerFooter';
const MainStyled = styled.main`
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 10px;
  margin-left: 120px;
  margin-bottom: 4%;
`;
const InputContainerStyled = styled.div`
  display: flex;
  align-items: center;
  width: 50%;
  flex-direction: column;
  gap: 20px;
  padding: 20px;
`;

export const Index = () => {
  const [showPassword, setShowPassword] = useState(false);
  const handleClick = () => setShowPassword(!showPassword);
  return (
    <>
      <Head>
        <title>SignUp Page</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <Box
        display={'flex'}
        justifyContent={'space-around'}
        alignItems={'center'}
        height={'100px'}
        width={'50%'}
        marginLeft={'25%'}
      >
        <Link href='/'>
          <BackIcon />
        </Link>
        <Heading as={'h1'} color={'teal'} fontWeight={700}>
          Sign Up
        </Heading>
      </Box>
      <MainStyled>
        <InputContainerStyled>
          <Input
            placeholder='Name'
            size='lg'
            variant='flushed'
            focusBorderColor='#4267B2'
          />
          <Input
            placeholder='Registration No.'
            size='lg'
            variant='flushed'
            focusBorderColor='#4267B2'
          />
          <Input
            type='email'
            size='lg'
            placeholder='Email'
            variant='flushed'
            focusBorderColor='#4267B2'
          />
          <InputGroup size='lg'>
            <Input
              pr='20px'
              type={showPassword ? 'text' : 'password'}
              placeholder='Password'
              size='lg'
              variant='flushed'
              focusBorderColor='#4267B2'
            />
            <InputRightElement width='4.5rem'>
              <Button h='1.75rem' size='sm' onClick={handleClick}>
                {showPassword ? 'Hide' : 'Show'}
              </Button>
            </InputRightElement>
          </InputGroup>
          <Button
            colorScheme='green'
            variant='solid'
            mt={10}
            width={'50%'}
            fontSize={'20px'}
          >
            Sign Up
          </Button>
        </InputContainerStyled>
      </MainStyled>
      <InnerFooter />
    </>
  );
};
export default Index;
