import Head from 'next/head';
import { Button } from '@chakra-ui/button';
import { InputGroup, InputRightElement, border } from '@chakra-ui/react';
import { styled } from 'styled-components';
import { Heading } from '@chakra-ui/react';
import { Input } from '@chakra-ui/react';
import { useState } from 'react';
import { FormControl, FormLabel } from '@chakra-ui/react';

const MainStyled = styled.main`
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 10px;
  margin: 120px 0;
`;
const InputContainerStyled = styled.div`
  display: flex;
  align-items: center;
  width: 50%;
  flex-direction: column;
  gap: 20px;
  padding: 20px;
`;

export const Index = () => {
  const [showPassword, setShowPassword] = useState(false);
  const handleClick = () => setShowPassword(!showPassword);
  return (
    <>
      <Head>
        <title>SignUp Page</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <MainStyled>
        <Heading
          as='h2'
          size='3xl'
          fontFamily='Georgia'
          fontWeight='bold'
          color='#4267B2'
          mb={15}
        >
          SignUp
        </Heading>

        <InputContainerStyled>
          <Input
            placeholder='Name'
            size='lg'
            variant='flushed'
            focusBorderColor='#4267B2'
          />
          <Input
            placeholder='Registration No.'
            size='lg'
            variant='flushed'
            focusBorderColor='#4267B2'
          />
          <Input
            type='email'
            size='lg'
            placeholder='Email'
            variant='flushed'
            focusBorderColor='#4267B2'
          />
          <InputGroup size='lg'>
            <Input
              pr='20px'
              type={showPassword ? 'text' : 'password'}
              placeholder='Password'
              size='lg'
              variant='flushed'
              focusBorderColor='#4267B2'
            />
            <InputRightElement width='4.5rem'>
              <Button h='1.75rem' size='sm' onClick={handleClick}>
                {showPassword ? 'Hide' : 'Show'}
              </Button>
            </InputRightElement>
          </InputGroup>
          <Button colorScheme='green' variant='solid' mt={10}>
            Sign Up
          </Button>
        </InputContainerStyled>
      </MainStyled>
    </>
  );
};
export default Index;
