export default function Home() {
  return (
    <>
      <title>HomePage</title>
      <meta name='description' content='Generated by create next app' />
      <meta name='viewport' content='width=device-width, initial-scale=1' />
      <main>
        <h1>Hello welcome to my page</h1>
      </main>
    </>
  );
}
