import Head from 'next/head';
import Logo from '@/components/Logo/Logo';
import { MdBuild, MdCall } from 'react-icons/md';
import { Button } from '@chakra-ui/button';
import { Stack } from '@chakra-ui/react';
import { styled } from 'styled-components';

const LoginButtonsWrapperStyled = styled.div`
  margin: auto;
`;

export const index = () => {
  return (
    <>
      <Head>
        <title>HomePage</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>

      <main>
        <Logo
          alt='IUST-logo'
          href='google.com'
          width={200}
          height={65}
          imgSrc='next.svg'
        />
        <LoginButtonsWrapperStyled>
          <Stack direction='row' spacing={4}>
            <Button leftIcon={<MdBuild />} colorScheme='pink' variant='solid'>
              Settings
            </Button>
            <Button rightIcon={<MdCall />} colorScheme='blue' variant='outline'>
              Call us
            </Button>
          </Stack>
        </LoginButtonsWrapperStyled>
      </main>
    </>
  );
};
export default index;
